<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get admin by admin_id
     */
    function get_admin($admin_id)
    {
        return $this->db->get_where('admin',array('admin_id'=>$admin_id))->row_array();
    }
        
    /*
     * Get all admin
     */
    function get_all_admin()
    {
        $this->db->order_by('admin_id', 'desc');
        return $this->db->get('admin')->result_array();
    }
        
    /*
     * function to add new admin
     */
    function add_admin($params)
    {
        $this->db->insert('admin',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update admin
     */
    function update_admin($admin_id,$params)
    {
        $this->db->where('admin_id',$admin_id);
        return $this->db->update('admin',$params);
    }
    
    /*
     * function to delete admin
     */
    function delete_admin($admin_id)
    {
        return $this->db->delete('admin',array('admin_id'=>$admin_id));
    }
}
