<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perahu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perahu by perahu_id
     */
    function get_perahu($perahu_id)
    {
        return $this->db->get_where('perahu',array('perahu_id'=>$perahu_id))->row_array();
    }
        
    /*
     * Get all perahu
     */
    function get_all_perahu()
    {
        $this->db->order_by('perahu_id', 'desc');
        return $this->db->get('perahu')->result_array();
    }
        
    /*
     * function to add new perahu
     */
    function add_perahu($params)
    {
        $this->db->insert('perahu',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perahu
     */
    function update_perahu($perahu_id,$params)
    {
        $this->db->where('perahu_id',$perahu_id);
        return $this->db->update('perahu',$params);
    }
    
    /*
     * function to delete perahu
     */
    function delete_perahu($perahu_id)
    {
        return $this->db->delete('perahu',array('perahu_id'=>$perahu_id));
    }
}
