<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perahu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perahu_model');
    } 

    /*
     * Listing of perahu
     */
    function index()
    {
        $data['perahu'] = $this->Perahu_model->get_all_perahu();
        
        $data['_view'] = 'perahu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new perahu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama_perahu' => $this->input->post('nama_perahu'),
				'nama_pemilik' => $this->input->post('nama_pemilik'),
				'foto_path' => $this->input->post('foto_path'),
				'no_perahu' => $this->input->post('no_perahu'),
				'tahun' => $this->input->post('tahun'),
				'kapasitas' => $this->input->post('kapasitas'),
				'harga' => $this->input->post('harga'),
				'created_at' => $this->input->post('created_at'),
				'spesifikasi_perahu' => $this->input->post('spesifikasi_perahu'),
            );
            
            $perahu_id = $this->Perahu_model->add_perahu($params);
            redirect('perahu/index');
        }
        else
        {            
            $data['_view'] = 'perahu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a perahu
     */
    function edit($perahu_id)
    {   
        // check if the perahu exists before trying to edit it
        $data['perahu'] = $this->Perahu_model->get_perahu($perahu_id);
        
        if(isset($data['perahu']['perahu_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama_perahu' => $this->input->post('nama_perahu'),
					'nama_pemilik' => $this->input->post('nama_pemilik'),
					'foto_path' => $this->input->post('foto_path'),
					'no_perahu' => $this->input->post('no_perahu'),
					'tahun' => $this->input->post('tahun'),
					'kapasitas' => $this->input->post('kapasitas'),
					'harga' => $this->input->post('harga'),
					'created_at' => $this->input->post('created_at'),
					'spesifikasi_perahu' => $this->input->post('spesifikasi_perahu'),
                );

                $this->Perahu_model->update_perahu($perahu_id,$params);            
                redirect('perahu/index');
            }
            else
            {
                $data['_view'] = 'perahu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The perahu you are trying to edit does not exist.');
    } 

    /*
     * Deleting perahu
     */
    function remove($perahu_id)
    {
        $perahu = $this->Perahu_model->get_perahu($perahu_id);

        // check if the perahu exists before trying to delete it
        if(isset($perahu['perahu_id']))
        {
            $this->Perahu_model->delete_perahu($perahu_id);
            redirect('perahu/index');
        }
        else
            show_error('The perahu you are trying to delete does not exist.');
    }
    
}
